AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

Lint/ScriptPermission:
  Enabled: False

Layout/EndOfLine:
  Enabled: False