module Urm
  class Instruction
    def self.dec: (Integer) -> Instruction
    def self.if: (Integer, Integer, Integer) -> Instruction
    def self.inc: (Integer) -> Instruction

    def self.parse: -> Instruction

    def self.set: (Integer, Integer) -> Instruction
    def self.stop: () -> Instruction

    attr_reader label_false: Integer?
    attr_reader label_true: Integer?
    attr_reader register: Integer?
    attr_reader type: Symbol
    attr_reader value: Integer?
  end
end
