module Urm
  class Machine

    attr_reader instructions: Array[Instruction]
    attr_reader registers: Array[Integer]

    def add: -> void
    def run: -> void

    def validate_instructions: -> void

  end
end
